"""add description_embedding to reports

Revision ID: 242731ee80d4
Revises: 8d99a243f666
Create Date: 2026-06-04 00:04:19.268254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242731ee80d4'
down_revision: Union[str, None] = '8d99a243f666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('description_embedding', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'description_embedding')
    # ### end Alembic commands ###
