"""add ai_confidence to reports

Revision ID: 8d99a243f666
Revises: 5e94593b9fe9
Create Date: 2026-05-31 21:48:49.037727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d99a243f666'
down_revision: Union[str, None] = '5e94593b9fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_cluster_rep_report', 'duplicate_clusters', 'reports', ['representative_report_id'], ['report_id'], use_alter=True)
    op.create_index('ix_locations_geog', 'locations', ['geog'], unique=False, postgresql_using='gist')
    op.add_column('reports', sa.Column('ai_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'ai_confidence')
    op.drop_index('ix_locations_geog', table_name='locations', postgresql_using='gist')
    op.drop_constraint('fk_cluster_rep_report', 'duplicate_clusters', type_='foreignkey')
    # ### end Alembic commands ###
